version: '3'

services:
    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - 8000:8000
      volumes:
        - ./backend:/app/backend
      depends_on:
        - db
      networks:
        - talkerApp
    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      tty: true
      ports:
        - 50000:3000
      volumes:
        - ./frontend:/app/backend
      depends_on:
        - backend
      networks:
        - talkerApp
    db:
      image: arm64v8/mysql:oracle
      restart: unless-stopped
      container_name: database
      environment:
        MYSQL_ROOT_PASSWORD: f2-N+grA4qJ3%b2y
        MYSQL_DATABASE: 'talkerApp'
      ports:
        - 34253:3306
      networks:
        - talkerApp

networks:
  talkerApp:
    driver: bridge
    name: 'talkerApp'